### ISSUE TITLE
If multiple sliders exist on the same page, only the first one functions correctly

### ISSUE THREAD

**Issue by jasonmorehead** [mmonkey/fireSlider#12]

**Comment by mmonkey** [comment]
Re-factored codebase to work with multiple sliders on the same page.

**Comment by jasonmorehead** [comment]
Unfortunately, there are still some glitches with the pagination and next/previous controls if there are multiple spotlights and they both have those controls active.

1) The pagination controls will control their respective slideshows, but the controls themselves are lumped together. See screenshot below.

![screen shot 2015-02-16 at 10 04 27 am](https://cloud.githubusercontent.com/assets/1703762/6215099/37f12de0-b5c3-11e4-8984-e648f9e495bc.png)

2) The next/previous links on the first spotlight actually control the last slider on the page. For any other sliders on the page, the next/previous links don't do anything.

**Comment by mmonkey** [comment]
@jasonmorehead I can fix the pager, prev/next by crawling the dom and finding the closest match to the selector. Does this sound good?

**Comment by mmonkey** [comment]
Pager, prev and next elements with the same class selector fixed in: https://github.com/mmonkey/fireSlider/releases/tag/v1.2.4
