### ISSUE TITLE
Handle breakpoints via data attributes

### ISSUE THREAD

**Issue by jasonmorehead** [mmonkey/fireSlider#14]

**Comment by mmonkey** [comment]
Added in https://github.com/mmonkey/fireSlider/releases/tag/v1.2.1

**Comment by jasonmorehead** [comment]
I can't get the "data-fireslider-breakpoints" attribute to work. Here's my code:

```
<ul
    data-fireslider-prev=".slider-prev"
    data-fireslider-next=".slider-next"
    data-fireslider-active-slide-class="slide--active"
    data-fireslider-pager=".slider-pager"
    data-fireslider-active-pager-class="slider-pager__here"
    data-fireslider-breakpoints='[
        {"breakpoint": 480, "show": 1, "active": 1},
        {"breakpoint": 992, "show": 2, "active": 1},
        {"breakpoint": 1200, "show": 3, "active": 2}
    ]'>
    <li class="slide slide--1">

        <div class="slide__image">
            <img src="../_theme/photos/1.jpg">
        </div>

    </li>
    <li class="slide slide--2">

        <div class="slide__image">
            <img src="../_theme/photos/2.jpg">
        </div>

    </li>
    <li class="slide slide--3">

        <div class="slide__image">
            <img src="../_theme/photos/3.jpg">
        </div>

    </li>
</ul>
```

What am I doing wrong?

**Comment by jasonmorehead** [comment]
Note: The "data-fireslider-show" and "data-fireslider-active" attributes work just fine.

**Comment by cjohara** [comment]
I tested the breakpoints and they are working as expected. The rule of breakpoints works like this:
- If the window is sized at the "breakpoint" or smaller, it uses the active and show attribute.
- If you want any slider that is 1200px or wider to have 3 showing:
  - `data-fireslider-show="3" data-fireslider-active="2"`.
- If you want any slider that is under 1200px wide to have 2 showing:
  - `data-fireslider-breakpoints='[{"breakpoint": 1199, "show": 2, "active": 1}]'`
- So the breakpoint is "less than or equal to" the set breakpoint size, everything outside of that range (larger than 1199px in this example) will take on the show and active options passed in.

**Comment by jasonmorehead** [comment]
@cjohara Could you update fireSlider so that the breakpoints work like the rest of Design 2.0, i.e., breakpoints are "greater than or equal to"?

**Comment by mmonkey** [comment]
Updated in: https://github.com/mmonkey/fireSlider/releases/tag/v1.2.4
