### ISSUE TITLE
FireSlider doesn't work in IE versions older than 11

### ISSUE THREAD

**Issue by jasonmorehead** [mmonkey/fireSlider#21]
I know we don't officially support IE9 but...

**Comment by mmonkey** [comment]
I'll check into this over the weekend

**Comment by mmonkey** [comment]
After some very basic testing I have found out the following:
IE11 - Works great
IE10 & 9 - Doesn't load custom options (this may just be limited to data-attributes)
IE8 - Error "hasOwnProperty" is not a function

I will do some research and get these fixed. I don't think any of the problems in IE10, 9 or 8 are un-fixable.

**Comment by jasonmorehead** [comment]
I wouldn't worry too much about IE8 compatibility, FWIW.

**Comment by jasonmorehead** [comment]
I upgraded to v1.2.63 and it's still broken in IE9 and IE10. The basic slideshow functionality sort of works. However, there's no carousel functionality, the next/prev links don't work, and the pager controls aren't rendered.

**Comment by mmonkey** [comment]
IE9 and IE10 should be working now in: https://github.com/mmonkey/fireSlider/releases/tag/v1.3.0
As of right now, transitions are using translateX css properties. I am planning on adding IE8 compatible transitions in the near future.

**Comment by jasonmorehead** [comment]
v1.3.0 looks good in IE9-11.
