### ISSUE TITLE
IE9 compatibility?

### ISSUE THREAD

**Issue by jasonmorehead** [mmonkey/fireSlider#28]
The slider loads but no actual animations occur, and clicking on any nav elements does nothing.

**Comment by mmonkey** [comment]
I did some testing on the latest 1.4.3 and the jquery-fireslider branch and was unable to 'break' fireslider on ie9. Perhaps at the time of this issue, there was another bug causing this.

The transition to jquery.fireslider.js will happen soon, I will go back and re-test at that point.

**Comment by mmonkey** [comment]
Let's verify this is still a problem with v1.5.0, I think this should be resolved.
