### ISSUE TITLE
Is jQuery required now?

### ISSUE THREAD

**Issue by MattyBalaam** [mmonkey/fireSlider#35]
I'm a long-term Velocity user and recently come across this plugin to quickly add a slider to an existing site. The readme states that Velocity is the only dependency and that 

> Use with jQuery
> 
> You can take advantage of jQuery, if you choose to do so.

Which suggested to me that it would work without jQuery.

I have jQuery on the site in a dev environment as it is used by some debugging tools. fireSlider works fine here, but once in live mode I get the following error.

```
ReferenceError: jQuery is not defined[Learn More]
```

**Comment by mmonkey** [comment]
Yes, it now requires jQuery. The jQuery library just handles browser compatibility much better. I will need to update the documentation.
