### ISSUE TITLE
0 width containers cause fireslider to kill page - divide by zero

### ISSUE THREAD

**Issue by tylerfowle** [mmonkey/fireSlider#38]
situations where the calculated with of a slide is a very small number,  ie < 10 then performance takes a hit

`display: none` will cause the width to be zero

- [x] check for dividing by zero
- [x] set max limit of duplicated slides

**Comment by mmonkey** [comment]
Please checkout the latest version on the develop branch to test out

**Comment by mmonkey** [comment]
released in v1.5.6
