### ISSUE TITLE
Create a variable for the start position values

### ISSUE THREAD

**Issue by astuefer** [mmonkey/fireSlider#43]
Allow a user to pass through the start position values on lines 357, 360, 375, and 391. We've ran into some design instances where we need the slides to overlap and adding the ability to override the `100` value with something else would allow us to customize the slider without copying over the entire library.

![Screen Shot 2020-05-26 at 1 34 40 PM](https://user-images.githubusercontent.com/4910380/82937364-ab1c0c00-9f55-11ea-9f62-c1b0e1c9403b.png)

**Comment by mmonkey** [comment]
I just pushed an update ([v1.6.1](https://github.com/mmonkey/fireSlider/releases/tag/v1.6.1)) to support this. The setting is called "slideOffset" which takes a double (percent). In your example you'd set this to 75.0.

Let me know if this solves your issue.

**Comment by astuefer** [comment]
@mmonkey Thank you! I definitely didn't expect that quick of a response, but it is much appreciated!
