### ISSUE TITLE
Transition Triggers don't seem to work and/or add Trigger when slider auto-advances

### ISSUE THREAD

**Issue by astuefer** [mmonkey/fireSlider#46]
I need to key off a trigger that happens when the slider auto-advances on its own. It looks like either `fireSlider:transition:after` or `fireSlider:transition:before` should work, but it doesn't appear to actually trigger anything. 

example:
```
$('.news-container .news-list .news-articles').each(function () {
    var slider = $('.news-container .news-list .news-articles').fireSlider({
      delay: 6500,
      hoverPause: true,
      disableLinks: true,
      show: 3,
      prev: $('.news-container').find('.slider-nav--prev'),
      next: $('.news-container').find('.slider-nav--next'),
      slide: 'div',
      pager: $('#news-pager')
    });
    slider.on('fireSlider:transition:after', function (e) {
      console.log('next slide trigger');
      makeActiveSlide();
    });
```

If I change the trigger to `fireSlider:next`, the `makeActiveSlide()` function runs, but only if the next element is clicked. One way around this is to remove the auto-play on the slider, but I have a feeling that wouldn't be a desired solution.

**Comment by mmonkey** [comment]
What version of fireSlider are you using? I cannot duplicate the issue on the latest.

**Comment by astuefer** [comment]
@mmonkey It looks like we're still running `1.5.6` in the core (doh). I'll try to pull down the latest on this specific project and see if that corrects my issue.

I do see that `1.5.6` and the current version both have a trigger for `.on('fireSlider:play')`, but I'm not able to get it to work. 🤔 

```
$('.news-container .news-list .news-articles').each(function () {
    var slider = $('.news-container .news-list .news-articles').fireSlider({
      delay: 6500,
      hoverPause: true,
      disableLinks: true,
      show: 3,
      prev: $('.news-container').find('.slider-nav--prev'),
      next: $('.news-container').find('.slider-nav--next'),
      slide: 'div',
      pager: $('#news-pager')
    });
    slider.on('fireSlider:play', function (e) {
      console.log('next slide trigger');
      makeActiveSlide();
    });
```

Edit: Ah, nevermind. `:play` is only triggered when the slider is unpaused, not when it auto-slides.

Another edit: Ah, I think I see where the issue is. Looks like `fireSlider:transition:before` will handle what I'm after, but it isn't available in the version we're using. I'll double-check and confirm this shortly.

**Comment by astuefer** [comment]
@mmonkey Can confirm, using the latest gives me what I need. Sorry I didn't check that sooner! Closing out this issue.
